version: '3.4'

services:
  angular:
    image: angular
    build:
      context: angular
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
